export const SERVER = 'Server'
export const DATABASE = 'DataBase'
export const TABLE = 'Table'
export const COLUMN = 'Column'

export const ADD = 'ADD'
export const ADD_ICON = 'plus-circle'
export const DELETE = 'DELETE'
export const DELETE_ICON = 'minus-circle'
export const INFO = 'INFO'
export const INFO_ICON = 'info-circle'
export const PREVIEW = 'PREVIEW'
export const PREVIEW_ICON = 'eye'
export const DDL = 'DDL'
export const DDL_ICON = 'search'
export const EDIT = 'EDIT'
export const EDIT_ICON = 'edit'

export const PROCESSES = 'PROCESSES'
export const CONNECTIONS = 'CONNECTIONS'
export const MUTATIONS = 'MUTATIONS'
